openapi: 3.0.1
info:
  title: apimfunction
  description: Import from "apimfunction" Function App
  version: '1.0'
servers:
  - url: https://apim-dev-cicd.azure-api.net/apimfunction
paths:
  /http_trigger1:
    post:
      summary: http_trigger1
      description: http_trigger1
      operationId: http-trigger1
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]